services:
  - type: web
    name: stripe-terminal-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: STRIPE_SECRET_KEY
      sync: false
      - key: PORT
        value: 4242
